
TEX_FILES=core/front_matter.tex \
		  chapter1/overview.tex

photogrammetry-with-cpp.pdf: photogrammetry-with-cpp.tex $(TEX_FILES)
	pdflatex photogrammetry-with-cpp
	pdflatex photogrammetry-with-cpp



clean:
	rm *.pdf

